export const ACTION_TYPE = {
    SET_INITIAL_CATEGORIES: "SET_INITIAL_CATEGORIES",
    SET_INITIAL_PRODUCTS: "SET_INITIAL_PRODUCTS",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    SORT_BY_PRICE:"SORT_BY_PRICE",
    SORT_BY_RATING:"SORT_BY_RATING",
    SORT_BY_CATEGORY:"SORT_BY_CATEGORY",
    GET_AUTH_TOKEN:"GET_AUTH_TOKEN"
    
  };
  