export const ACTION_TYPE = {
    SET_INITIAL_CATEGORIES: "SET_INITIAL_CATEGORIES",
    SET_INITIAL_PRODUCTS: "SET_INITIAL_PRODUCTS",
    ADD_TO_CART:"ADD_TO_CART",
    SORT_BY_PRICE:"SORT_BY_PRICE",
  };
  